spring:
  datasource:
    url: jdbc:mysql://localhost:3306/feed_inventory?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
        maximum-pool-size: 10
        minimum-idle: 5
        idle-timeout: 600000
  ai:
    zhipuai:
      client:
        connect-timeout: 5000
        read-timeout: 60000
    vectorstore:
      chroma:
        client:
          host: api.trychroma.com
        collection:
          name: customer-support-messages
        embedding:
          dimension: 384
    mcp:
      client:
        name: spring-ai-mcp-client
        sse:
          connections:
            server1:
              url: http://localhost:9090
              sse-endpoint: /sse
        toolcallback:
          enabled: true
  application:
    name: spring-ai
server:
  servlet:
    context-path: /spring-ai
  port: 8090
